#pragma once
enum class PostEffectType {
    Copy,
    GrayScale,
    Vignette,
    DepthOfField,
    MotionBlur,
    ChromaticAberration,
    LensDistortion,
    FilmGrain,
    LensDirt,
    CameraShake,
    BokehShape,
    Fisheye,
    Pixelate,
    ColorAdjust,
    smoothing,
    GaussianFilter,
    LuminanceBasedOutline,
    DepthOutline,
    RadialBlur,
    Dissolve,
    Random,
    Bloom,
    LensFlare,
    Glare,
    LightShafts,
    VolumetricLight,
    AnamorphicFlare,
    Halo,
    LightStreak,
    NeonGlow,
    GhostImage,
    Outline,
    Fog,
    FocusLine,
    Paint,
    GlassCrack,
};

const char* GetPostEffectTypeName(PostEffectType type);
