<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <SolutionDir Condition="'$(SolutionDir)' == '' Or '$(SolutionDir)' == '*Undefined*'">$(MSBuildThisFileDirectory)..\..\</SolutionDir>
  </PropertyGroup>
  <Import Project="..\..\KohakuEngine.vcxproj" />
  <PropertyGroup>
    <ProjectName>SoundManagerTests</ProjectName>
    <LocalDebuggerWorkingDirectory>$(projectRootPath)</LocalDebuggerWorkingDirectory>
    <TargetName>SoundManagerTests</TargetName>
    <IntDir>$(projectRootPath)..\generated\obj\SoundManagerTests\$(Platform)\$(Configuration)\</IntDir>
    <OutDir>$(projectRootPath)..\generated\outputs\$(Configuration)\</OutDir>
    <TargetFileName>SoundManagerTests.exe</TargetFileName>
    <TargetPath>$(OutDir)SoundManagerTests.exe</TargetPath>
  </PropertyGroup>
  <ItemDefinitionGroup><Link><SubSystem>Console</SubSystem></Link></ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Remove="@(ClCompile)" />
    <ClCompile Include="$(projectRootPath)Engine\audio\SoundManager.cpp" />
    <ClCompile Include="$(projectRootPath)Engine\StringUtility\StringUtility.cpp" />
    <ClCompile Include="$(projectRootPath)Engine\Logger\Logger.cpp" />
    <ClCompile Include="$(projectRootPath)Tests\SoundManagerTests.cpp" />
  </ItemGroup>
</Project>
