<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="CG2_LE2C_FUJII.vcxproj" />
  <PropertyGroup>
    <ProjectName>SoundManagerTests</ProjectName>
    <TargetName>SoundManagerTests</TargetName>
    <IntDir>$(ProjectDir)..\generated\obj\SoundManagerTests\$(Platform)\$(Configuration)\</IntDir>
    <OutDir>$(ProjectDir)..\generated\outputs\$(Configuration)\</OutDir>
    <TargetFileName>SoundManagerTests.exe</TargetFileName>
    <TargetPath>$(OutDir)SoundManagerTests.exe</TargetPath>
  </PropertyGroup>
  <ItemDefinitionGroup><Link><SubSystem>Console</SubSystem></Link></ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Remove="@(ClCompile)" />
    <ClCompile Include="Engine\audio\SoundManager.cpp" />
    <ClCompile Include="Engine\StringUtility\StringUtility.cpp" />
    <ClCompile Include="Engine\Logger\Logger.cpp" />
    <ClCompile Include="Tests\SoundManagerTests.cpp" />
  </ItemGroup>
</Project>
